es6/2015-03/mar-24.md

fix presentation link

---

es7/2015-09/sept-22.md
es7/2015-09/sept-23.md
es7/2015-09/sept-24.md

fixes some typo and format code block.
/cc @rwaldron

Fix some typo in 2015-09

---

es6/2015-01/jan-27.md
es6/2015-01/jan-28.md

Just some small typo fixes
/cc @rwaldron

Some minor typo fixes

---

es7/2015-11/nov-17.md
es7/2015-11/nov-18.md
es7/2015-11/nov-19.md

Fixes #36.
Happy to fix any markdown formatting issues.

Add November 2015 TC39 meeting notes.

---

es7/2015-11/nov-17.md
es7/2015-11/nov-18.md
es7/2015-11/nov-19.md

Fixes some typo and fix indent.
/cc @rwaldron @ljharb

Fix some typo in 2015-11

---

es7/2016-01/2016-01-26.md

Fix slide's link

---

es7/2016-01/2016-01-26.md
es7/2016-01/2016-01-27.md
es7/2016-01/2016-01-28.md

Hi, I fixed many typos. :) 
If you found error, let me know.
I will revert the commit which is error. 
Thanks.
/cc @rwaldron

Fix typos in 2016-01

---

es7/2016-03/march-29.md
es7/2016-03/march-30.md
es7/2016-03/march-31.md

Fix some typos and add/fix link to slide.
/cc @bterlson @rwaldron

Fix typos in 2016-03

---

es7/2016-03/march-29.md

Also, "woudl be bettter to adddres" -> "would be better to address".

Fix link to the last meeting agenda

---

es7/2016-05/may-23.md
es7/2016-05/may-24.md
es7/2016-05/may-25.md

This PR is up to date with the last editions in the notes

Add meeting notes for 2016-05

---

es7/2016-05/may-24.md
es7/2016-05/may-25.md

Fix some typos.
/cc @rwaldron @leobalter

Fix typo in 2016-05

---

es7/2016-09/sept-27.md
es7/2016-09/sept-28.md
es7/2016-09/sept-29.md

Fix typo and broken markdown.
/cc @rwaldron

Fix some typo in 2016-09

---

es6/2013-09/sept-18.md

Escape `__iterator__` in 2013-09

---

es8/2017-03/mar-21.md
es8/2017-03/mar-22.md
es8/2017-03/mar-23.md
es8/2017-03/summary.md

the folder structure is weird, but I'm trying to capture the essence of it.
I already changed my initials to avoid conflict with a pre-existing LB (Lee Byron)
I'll open another PR to change my LB initials to LBR as well.

March 2017 meeting notes

---

es8/2017-03/mar-22.md
es8/2017-03/mar-23.md

Hi, I've fixed some typo and add some links.
/cc @rwaldron @leobalter

Fix some typo in 2017-03

---

es8/2017-03/mar-21.md

Follow-up to 32fd7b60a40531c74c93bd99142c5a125fc54f6a.

Add link to Unicode property escapes proposal

---

scripts/builder.js

Fix links to markdown files in html

---

scripts/builder.js

Add <title> to index page

---

es8/2017-07/jul-25.md
es8/2017-07/jul-26.md
es8/2017-07/jul-27.md

This PR fixed following:
- Fix some typo
- Fix 404 link
/cc @rwaldron

Fix some things in 2017-07

---

es8/2017-07/summary.md

Temporal is still on stage 1, not yet stage 2.  Thanks.

Corrected stage number for temporal proposal

---

es8/2017-09/sep-26.md
es8/2017-09/sep-27.md
es8/2017-09/sep-28.md
es8/2017-09/summary.md

~~The summary is not ready yet, but it should not block the release of the notes.~~

Add meeting notes for Sept 2017

---

es8/2018-01/summary.md

It was going for Stage 0 -> 2 advancement, but we only promoted it to Stage 1.

Array.p.last was a new proposal

---

es9/2018-07/summary.md

@rwaldron @leobalter  Please take a look !

Add summary for July 2018 meeting 

---

es9/2018-09/summary.md

add summary for TC39  66the meeting.

---

es9/2018-05/may-22.md
es9/2018-05/may-23.md
es9/2018-05/may-24.md
es9/2018-05/summary.md

Fix some typo and markdown syntax.

Fix things in 2018-05

---

meetings/2019-07/july-23.md

fix missing slides link
